beltoforion/muparser

src/muParserDLL.cpp

these should be either declared, static or inlined

fix gcc warning about undeclared functions

---

CMakeLists.txt

- LIB_SUFFIX is unused now
- MUPARSER_DLL controls the inclusion of the C interface and does not depend on BUILD_SHARED_LIBS
- MUPARSERLIB_EXPORTS should be only defined to export symbols for shared builds else we define MUPARSER_STATIC (TODO: export C++ symbols)
- no SHARED, DEBUG (only _DEBUG) definitions
- example2.c can be compiled now that MUPARSER_DLL is defined
- removed add_test as samples are blocking (TODO: add C&C++ tests)

Fix compile definitions

---

CMakeLists.txt
include/muParserBase.h
include/muParserToken.h
src/muParserTest.cpp
src/muParserTokenReader.cpp

Fixes #29. At least `libc++` started to remove `std::auto_ptr` from their implementation of the C++ standard library. In particular, Apple's `clang-9.1.0` which uses `libc++` by default refuses the existence of `std::auto_ptr` if compiled with `std=c++17` and we are running into this issue in dealii/dealii#6125.
Hence, it seems to be time to replace it by `std::unique_ptr`.

Replace std::auto_ptr by std::unique_ptr

---

src/muParserTokenReader.cpp

`clang-tidy` suggests using a single character instead of a single character string. https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html

Avoid using single character string in muParserTokenReader

---

CMakeLists.txt
include/muParser.h
include/muParserBase.h
include/muParserCallback.h
include/muParserDLL.h
include/muParserError.h
include/muParserFixes.h
include/muParserTest.h

The new API_EXPORT_CXX macro exports c++ symbols and is used to declare exported classes.
This fixes #41.

Export C++ symbols

---

CMakeLists.txt

This pull request allows the complete library repo to be included as subdirectory of an existing project.
When I included the repo as submodule, I got a "file not found error" of the muParser.h header file. I traced it back to the use of a specific CMAKE variable when adding the include path. According to https://stackoverflow.com/questions/53195186/difference-between-cmake-current-source-dir-cmake-source-dir-variables, CMAKE_CURRENT_SOURCE_DIR should be used instead of CMAKE_SOURCE_DIR.

Allow compilation as CMAKE subdirectory

---

CMakeLists.txt

This pull request prevents the need for a target linking to muparser to manually add the muParser include directory.
When consuming muParser in my project via `add_subdirectory()`, I received the fatal error: `muParser.h: No such file or directory`, so I had to manually add the include directory to my target.
Using `target_include_directories()` with scope `PUBLIC` instead of `include_directories()` allows to propagate the muparser include directory to all targets that link to it, as `include_directories()` only adds the include directories to targets in the current CMakeLists file.
CMake documentation at https://cmake.org/cmake/help/latest/command/include_directories.html states that `target_include_directories()` should be preferred to add include directories to individual targets and …

Propagate muparser include directories to all dependent targets

---

CMakeLists.txt
muparserConfig.cmake.in
samples/example3/CMakeLists.txt
samples/example3/README.md
samples/example3/build.sh
samples/example3/example3.cpp

Export muparser targets, such that client projects can
import it using find_package(). This mechanism for both the build tree
and the install tree. The provided example3 shows how to import muparser
targets.
Signed-off-by: Francis Giraldeau <francis.giraldeau@nrc-cnrc.gc.ca>

Export muparser cmake targets

---

CMakeLists.txt

This PR allows for disabling tests by setting BUILD_TESTING (built-in) option to OFF.
Tests are enabled by default.

Allow for conditionally disabling tests

---

include/muParser.h
include/muParserBase.h
include/muParserInt.h

This has been automatically corrected using clang-tidy, a small tutorial in here:
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Clang-Tidy-to-automatically-correct-code
Best regards

[Modern C++] Adding missing overrides

---

CMakeLists.txt
README.rst

Basically the title says. The manual definitions avoid issues with the MSVC (this for example happens with the Github CI we consider in our project: https://github.com/KratosMultiphysics/Kratos/pull/7899)

Adding manual definitions to avoid issues with MSVC. Update README with new changes

---

include/muParserCallback.h
include/muParserToken.h
src/muParserBase.cpp
src/muParserCallback.cpp

The goal of the out-of-line destructor, and of IsValid() instead of testing GetAddr() against nullptr, is to allow more backward binary compatible evolutions of ParserCallback (which has some impact on application binary code given the type is used through the method template ParserBase::DefineFun<>() )

trivial cleanup of ParserCallback & add methods

---

include/muParserBase.h
include/muParserBytecode.h
include/muParserCallback.h
include/muParserDLL.h
include/muParserDef.h
include/muParserTest.h
include/muParserToken.h
src/muParserBase.cpp
src/muParserBytecode.cpp
src/muParserCallback.cpp
src/muParserDLL.cpp
src/muParserTest.cpp

Note: this pull request includes both my previous ones: https://github.com/beltoforion/muparser/pull/97 "muParserDLL: add StrFun4 and StrFun5 support" and https://github.com/beltoforion/muparser/pull/98 "trivial cleanup of ParserCallback & add methods"
For a big historical unpublished code base, we need user data on custom defined functions.
The present pull request proposes that, in a backward binary compatible way. I can simplify it if binary compat is not needed.
If you are not interested by the feature, can you please evaluate taking the two previous pull requests + the patch https://github.com/gknispel/muparser/commit/1a70008992d6d7bfd10b3a5d9d98027ceb61d8e2 "add mu::generic_callable_type: centralize the calls to fun_types, bulkfun_types, strfun_types, and multfun_type" ?
I'm open to …

add void* user data variants for fun, bulkfun, multfun, and strfun

---

include/muParserCallback.h
src/muParserCallback.cpp

muparser could potentially inject the value of cmFUNC in application
binary code through the template method ParserBase::DefineFun called
with a fun_type1, when it invokes ParserCallback(a_pFun, a_bAllowOpt)
However, e.g. commit d59959ad2f7e5e2 ("Macros for version number and
version data replaced with static constants"), between v2.2.6.1 and
v2.3.2, switched its value from 27 to 26.
Therefore, to enhance future binary compatibility robustness (with
application code compiled after the present patch) in case of further
changes of ECmdCode, the present patch splits ParserCallback(
fun_type1, [...]) into two overloads without default values: one for
usage through ParserBase::DefineFun* by application code, and one for
internal usage by muparser.  For now (and until cmFUNC changes, if it …

ParserCallback(fun_type1, [...]): split into two instead of using default values

---

CMakeLists.txt
muparser.pc.in

If you compile muParser with wchar support and use pkg-config, the `_UNICODE` define is missing.
Assume you have a code like:
```cxx
#include <muParser.h>
int main() {
return 0;
}
void ExpressionParser(const std::string& expression){
std::unique_ptr<mu::Parser> parser = std::make_unique<mu::Parser>();
parser->SetExpr(expression);
}
```
and compile it with
```
g++ `pkg-config --libs --cflags muparser` main.cpp
```
it will fails with:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccMowORw.o: in function `ExpressionParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text+0x4d): undefined reference to `mu::ParserBase::SetExpr(std::__cxx11::basic_string<char, std::char_traits<char>, …
```

cmake: also inject -D_UNICODE into muparser.pc

---

CMakeLists.txt

Use the OpenMP::OpenMP_CXX target to more robustly provide access to `omp.h`. Also improves compatibility with a parent build system when embedded in a dependent project.

Use OpenMP CMake target.

---

CMakeLists.txt

Useful when using bundled copy of muparser

cmake: add namespaced alias target

---

src/muParserTest.cpp

We found a warning while transitioning from the classic Intel compiler `icpc` to the new IntelLLVM compiler `icpx` that occurs in fast math mode. See also https://github.com/dealii/dealii/issues/15301.
```
/muparser_v2_3_3/src/muParserTest.cpp:1558:38: error: explicit comparison with infinity in fast floating point mode [-Werror,-Wtautological-constant-compare]
bCloseEnough &= (fabs(fVal[i]) != numeric_limits<value_type>::infinity());
~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The following patch suggests to use `std::isfinite` rather than a comparison with infinity. We can confirm that the warning no longer shows up.
The classic Intel compiler will be retired later in 2023.

Fix problem with IntelLLVM fast math

---

include/muParserTokenReader.h

Fixes `undefined reference to `mu::ParserTokenReader::ParserTokenReader(mu::ParserBase*)'` in Windows builds.

missing dll macro for ParserTokenReader class for Windows builds

---

include/muParserTemplateMagic.h

The NEC compiler (https://sxauroratsubasa.sakura.ne.jp/Documentation) complains that std::min is not known here. Adding the include for algorithm, where it is defined (https://en.cppreference.com/w/cpp/algorithm/min) resolves the issue and lets muParser successfully compile with it.

Include <algorithm> in muParserTemplateMagic.h

---

src/muParserBase.cpp

Issues were encountered when using NVC++ compiler and ScoreP wrapper. Those are compiler bugs, but extracting the chunk size not only avoids the problem, but also makes the code (subjectively) easier to read.

Simplify OpenMP clause to avoid compiler bugs

---

CMakeLists.txt

By default, `find_package(OpenMP)` will run detection for all enabled languages. This is slightly wasteful since only C++ flags are needed, and can cause troubles when muParser is bundled in a project which has other languages enabled but their OpenMP support is broken.

Only detect OpenMP flags for C++
